config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :paintings, only: [:index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :bookings, only: [ :edit, :update, :create ]
  end
  get "/dashboard", to: "pages#dashboard", as: :dashboard

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_booking_card.html.erb
<div class="container">
  <div class="message">
    <img class="avatar-large" src="<%= booking.painting.photo %>">
    <div class="message-name">
      <h3><%= "Painting Title" %></h3>
      <p><%= "#{booking.painting.name}" %></p>
    </div>
    <div class="message-body">
      <p><strong><%= "BOOKING N°00#{booking.id}" %></strong></p>
      <p><%= "Title : #{booking.painting.name}" %></p>
      <p><%= "Author : #{booking.painting.author}" %></p>
      <p><%= "Rent from #{booking.start_date} to #{booking.end_date}" %></p>
    </div>
    <div class="message-status">
      <p class="status pending">Done</p>
      <p class="price"><%= "#{booking.total_paid} €" %></p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert-fixed alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert-fixed alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <div class="navbar-wagon-brand">
    <%= link_to root_path, class: "navbar-wagon-brand flip-vertical-left" do %>
      <%= image_tag "FAP_Logo-flipH.png" %>
    <% end %>
    <div class="navbar-wagon-brand-title" style="font-family: 'Finger Paint', cursive; font-size: 30px; color: black;">FaP</div>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to 'Dashboard', dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
<!--           <img class="avatar dropdown-toggle" id="navbar-wagon-menu" src="<%= current_user.photo %>" "data-toggle" => "dropdown" > -->
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
<!--             <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%#= t(".settings", default: "Settings") %>
              <%# end %>
            </li> -->
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", height: 30, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to new_user_session_path do %>
                <i class="fa fa-user"></i> <%= t(".sign_in", default: "Log in") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus"></i> <%= t(".sign_up", default: "Sign up") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'Dashboard', dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Sign up", new_user_registration_path , class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_painting_card.html.erb
<% require 'date' %>

<div class="col-xs-12 col-sm-12 col-md-6">

  <figure class="snip1423">
    <%= cl_image_tag painting.photo, height: 200, width: 260, crop: :fill%>
    <figcaption>
      <h3><%= painting.name  %></h3>
      <p><%= painting.author  %></p>
      <div class="price">
        <%= painting.price %> € / day
      </div>
    </figcaption><i>Details</i>
    <%  if params[:paintings][:start_date].empty? || params[:paintings][:end_date].empty? %>
      <%= link_to '', painting_path(painting.id, start_date: "", end_date: "")%>
    <% else %>
      <%= link_to '', painting_path(painting.id, start_date: params[:paintings][:start_date], end_date: params[:paintings][:end_date]) %>
    <% end %>
  </figure>
</div>

app/views/shared/_painting_edit.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <figure class="snip1423_sh">
    <%= cl_image_tag painting.photo, height: 280, crop: :fit%>
    <figcaption>
      <%= simple_form_for painting do |f| %>
        <%= f.input :name, input_html: { label: 'Title', value: painting.name, class: 'form-date' }, label_html: { class: 'form-label' } %>
        <%= f.input :author, input_html: { label: 'Author', value: painting.author, class: 'form-date' }, label_html: { class: 'form-label' } %>
        <%= f.input :style, input_html: { label: 'Style', value: painting.style, class: 'form-collection select2' }, label_html: { class: 'form-label-edit' }, collection: Painting::STYLES %>
        <p>Owner : <%= "#{painting.user.first_name} #{painting.user.last_name}" %></p>
        <i><%= f.submit "Update", class: 'avatar_book_btn' %></i>
      <% end %>
      </div>
  </figure>
</div>

app/views/shared/_painting_show.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <figure class="snip1423_sh">
    <%= cl_image_tag painting.photo, height: 280, crop: :fit%>
    <figcaption>
      <h3>Title : <%= painting.name  %></h3>
      <p>Author : <%= painting.author  %></p>
      <p>Style : <%= painting.style  %></p>
      <div class="price">
       Total Price : <%= total_paid %> €
      </div>
    <%= simple_form_for [painting, Booking.new] do |f| %>
      <%= f.input :start_date, label: 'Start Date', input_html: { value: start_date, class: 'form-date' } %>
      <%= f.input :end_date, label: 'End Date', input_html: { value: end_date, class: 'form-date' } %>
      <i><%= f.submit " Book ", class: 'avatar_book_btn' %></i>
    <% end %>
  </figure>
</div>

app/views/shared/_searchforminline.html.erb
<div>
  <h5>Not what you are looking for ?  Try again </h5>
</div>

<div class="form-inline">
  <form class="form-inline paintings" action="/paintings" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
    <div class="form-group paintings_location">
      <input class="form-control" placeholder="Type your address" type="text" name="paintings[location]" id="paintings_location">
    </div>
    <div class="form-group">
      <input class="form-control" placeholder="dd/mm/yyyy" type="text" name="paintings[start_date]" id="paintings_start_date">
    </div>
    <div class="form-group">
      <input class="form-control" placeholder="dd/mm/yyyy" type="text" name="paintings[end_date]" id="paintings_end_date">
    </div>
    <div class="form-group">
      <select class="form-control" placeholder="Choose in the list" name="paintings[style]" id="paintings_style"><option value=""></option>
        <option value="Abstract">Abstract</option>
        <option value="Abstraction">Abstraction</option>
        <option value="Expressionism">Expressionism</option>
        <option value="Impressionism">Impressionism</option>
        <option value="Modernism">Modernism</option>
        <option value="Painterly">Painterly</option>
        <option value="Photorealism">Photorealism</option>
        <option value="Realism">Realism</option>
      </select>

    </div>
    <div class="form-group">
      <input class="form-control" placeholder="Picasso"  type="text" name="paintings[author]" id="paintings_author">
    </div>
    <input type="submit" name="commit" value="Search" class="btn-list" data-disable-with="Search">
  </form>
</div>




      <!-- <input class="form-control select2" placeholder="Painterly" collection="Painting::STYLES" type="text" name="paintings[style]" id="paintings_style"> -->

<!-- novalidate="novalidate"  -->